# Generated by Django 4.0 on 2022-04-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pomodoro_minutes',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='pomodoro_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
