# Generated by Django 4.0 on 2022-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifiedusermodel',
            options={},
        ),
        migrations.AlterModelManagers(
            name='modifiedusermodel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='modifiedusermodel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='modifiedusermodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='modifiedusermodel',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='modifiedusermodel',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='modifiedusermodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modifiedusermodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modifiedusermodel',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile pictures/Avatar-13.png', upload_to='profile pictures/'),
        ),
    ]
