# Generated by Django 4.0 on 2022-04-03 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_pomodoro_minutes_profile_pomodoro_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pomodoro_minutes',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pomodoro_seconds',
            field=models.PositiveSmallIntegerField(default=59, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
    ]
