# Generated by Django 4.0 on 2022-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_modifiedusermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiedusermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
