# Generated by Django 4.0 on 2022-04-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modifiedusermodel_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiedusermodel',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
