# Generated by Django 4.0 on 2022-04-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_completed_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
    ]
